pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {
        stage('Pull') {
            steps {
                git url: "https://github.com/joshrobitaille/interview-prep.git", branch: "dev"
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test -Dcheckstyle.skip=true'
            }
        }
    //  stage('build && SonarQube analysis') {
    //         steps {
    //             withSonarQubeEnv('SonarCloud') {
    //                 // Optionally use a Maven environment you've configured already
    //                 // sh 'mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.branch.name=\"dev\"'
    //         sleep(10)
    //             }
    //         }
    //     }

        stage('build'){
            steps{
                sh 'mvn clean package'
            }
        }
        // stage("Quality Gate") {
        //     steps {
        //         timeout(time: 1, unit: 'HOURS') {
        //             waitForQualityGate abortPipeline: true
        //         }
        //     }
        // }
        stage('Upload Docker Image') {
            steps {
                script {
                   docker.withTool('docker') {
                        repoId = "joshrobitaille/simpleapp"
                        image = docker.build(repoId)
                        docker.withRegistry("https://registry.hub.docker.com", "dockerhoob") {
                            image.push()
                        }
                    }
                }
            }
        }
        stage('Rollout') {
            steps {
                    sh 'kubectl rollout restart deployment/sample-deployment'
            }
        }
    }
}