pipeline {

    agent any

    stages {
        stage('Build') {
            // Run the maven build
            steps {
                echo 'building..'
            }
        }
        stage('Test') {
            steps {
                echo 'testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'deploying..'
                // sh 'false'
            }
        }
    }
}